// ============================================
// Людмила Краузе — Художник, преподаватель
// Montserrat | Бирюзовый + цвета | RU/DE | Тёмная тема
// Фото: IndexedDB + статические fallback (из /images)
// ============================================

const translations = {
    ru: {
        logo: 'Мила Краузе',
        title: 'Людмила Краусе — Художник, преподаватель, арт-терапевт',
        nav_about: 'Обо мне',
        nav_services: 'Услуги',
        nav_reviews: 'Отзывы',
        nav_gallery: 'Галерея',
        nav_certificates: 'Сертификаты',
        nav_contact: 'Контакты',
        btn_contact: 'Связаться',
        hero_badge: 'Художник-педагог с 20-летним стажем',
        hero_title: 'Раскрываю творческий потенциал ребенка и взрослого через персональный подход',
        hero_text: 'Обучение живописи детей и взрослых, арт-терапия, Нейрографика, консультации по Квантовой Астрогенетике. Обучаю онлайн и офлайн в Ойскирхене, на русском и украинском языке, подходит для детей из русско-немецких семей.',
        badge_1: 'Индивидуальный подход',
        badge_2: 'Онлайн и офлайн',
        badge_3: 'Для детей и взрослых',
        btn_cta: 'Записаться на занятие',
        services_label: 'Услуги',
        services_title: 'Профессиональные компетенции и услуги',
        services_subtitle: 'Персональное обучение живописи, терапевтические практики, персональные консультации под запрос через квантовые инструменты',
        tag_kids: '5–15 лет',
        tag_teens: 'от 10 лет',
        tag_all: 'для всех',
        tag_online: 'онлайн',
        tag_consult: 'консультация',
        tag_individual: 'индивидуально',
        service_1_title: 'Рисование для детей',
        service_1_desc: 'Занятия для детей от 5 до 15 лет. Карандаш, акварель, акрил и развитие творческого мышления.',
        service_2_title: 'Масляная живопись',
        service_2_desc: 'Серьезные занятия для подростков и взрослых с углублением в технику масляной живописи. Раскрытие секретов и тонкостей создания полотен.',
        service_3_title: 'Арт-терапия',
        service_3_desc: 'Снятие стресса и эмоциональная гармонизация через творчество. Для детей и взрослых.',
        service_4_title: 'Нейрографика онлайн',
        service_4_desc: 'Практика, которая помогает проработать запросы и найти решения через рисунок. Доступно дистанционно.',
        service_5_title: 'Квантовая Астрогенетика',
        service_5_desc: 'Раскрытие планетарного потенциала ребенка и взрослого по дате рождения. Рекомендации по направлениям дальнейшего обучения и корректировке возможных психологических состояний.',
        service_6_title: 'Световые карты',
        service_6_desc: 'Квантовый инструмент работы с тонким планом через персональные световые метафорические расклады «Неопределенность событий возможно сделать определенными».',
        about_label: 'Обо мне',
        about_title: 'Творчество как путь к себе',
        about_p1: 'Верю, что каждый ребёнок талантлив по-своему, и моя задача — помочь этот талант раскрыть. Обучаю различным техникам живописи. К каждому ученику — индивидуальный подход. Учу детей рисовать карандашом, акрилом, маслом на холсте, развиваю творческое мышление и уверенность в себе.',
        about_p2: 'Помимо изобразительного искусства, я провожу арт-терапевтические занятия и нейрографику для детей и взрослых, помогаю снять стресс через творчество. Для родителей раскрываю планетарный потенциал детей по дате рождения.',
        quote: '«Каждый ребёнок талантлив по-своему, и я готова помочь раскрыть его потенциал».',
        float_years: 'лет опыта',
        photo_placeholder: 'Фото художника',
        stat_1: 'лет творческого опыта',
        stat_2: 'лет — возраст учеников',
        stat_3: 'направления искусства',
        stat_4: 'языки консультаций',
        gallery_label: 'Портфолио',
        gallery_title: 'Галерея',
        gallery_subtitle: 'Авторские работы и творчество учеников в различных техниках.',
        gallery_tab_personal: 'Личная',
        gallery_tab_students: 'Ученики',
        gallery_tab_neuro: 'Нейрографика',
        work_1: 'Работа 1',
        work_2: 'Работа 2',
        work_3: 'Работа 3',
        work_4: 'Работа 4',
        work_5: 'Работа 5',
        work_6: 'Работа 6',
        reviews_label: 'Отзывы',
        reviews_title: 'Что говорят ученики и родители',
        reviews_subtitle: 'Реальные отзывы от наших учеников и их родителей',
        video_label: 'Презентационное видео',
        contact_label: 'Контакты',
        contact_title: 'Свяжитесь со мной',
        contact_subtitle: 'Запишитесь на пробное занятие, задайте вопрос или узнайте больше об услугах',
        contact_info_title: 'Контакты',
        contact_info_text: 'Пишите или звоните — отвечу в удобное для вас время.',
        form_title: 'Записаться на занятие',
        form_text: 'Напишите мне в Telegram или WhatsApp или на электронную почту, и мы договоримся о времени и формате.',
        form_note: 'Занятия и консультации проходят в Ойскирхене, онлайн, возможны уроки на дому. Первое знакомство возможно онлайн в формате консультации, чтобы выбрать подходящий метод обучения или общения.',
        footer_text: '© 2026 Людмила Краусе. Все права защищены.',
        gallery_more: 'Больше работ',
        moreworks_title: 'Все работы — Людмила Краусе',
        moreworks_heading: 'Все работы',
        moreworks_subtitle: 'Полная коллекция работ и ученических проектов',
        moreworks_empty: 'Пока нет загруженных работ',
        certificates_label: 'Сертификаты',
        certificates_title: 'Мои сертификаты',
        certificates_subtitle: 'Подтверждение квалификации и профессионального развития'
    },

    de: {
        logo: 'Mila Krause',
        title: 'Ljudmila Krause — Künstlerin, Lehrerin, Kunsttherapeutin',
        nav_about: 'Über mich',
        nav_services: 'Leistungen',
        nav_reviews: 'Bewertungen',
        nav_gallery: 'Galerie',
        nav_certificates: 'Zertifikate',
        nav_contact: 'Kontakt',
        btn_contact: 'Kontakt',
        hero_badge: 'Kunstpädagogin mit 20 Jahren Erfahrung',
        hero_title: 'Entfalte das kreative Potenzial von Kindern und Erwachsenen durch einen persönlichen Ansatz',
        hero_text: 'Unterricht in Malerei für Kinder und Erwachsene, Kunsttherapie, Neurographik, Beratung in Quanten-Astrogenetik. Ich unterrichte online und offline in Euskirchen, auf Russisch und Ukrainisch, geeignet für Kinder aus russisch-deutschen Familien.',
        badge_1: 'Individueller Ansatz',
        badge_2: 'Online und Offline',
        badge_3: 'Für Kinder und Erwachsene',
        btn_cta: 'Termin vereinbaren',
        services_label: 'Leistungen',
        services_title: 'Berufliche Kompetenzen und Dienstleistungen',
        services_subtitle: 'Persönlicher Malunterricht, therapeutische Praktiken, persönliche Beratung auf Anfrage mit Quanteninstrumenten',
        tag_kids: '5–15 Jahre',
        tag_teens: 'ab 10 Jahren',
        tag_all: 'für alle',
        tag_online: 'online',
        tag_consult: 'Beratung',
        tag_individual: 'individuell',
        service_1_title: 'Zeichnen für Kinder',
        service_1_desc: 'Unterricht für Kinder von 5 bis 15 Jahren. Bleistift, Aquarell, Acryl und Entwicklung des kreativen Denkens.',
        service_2_title: 'Ölmalerei',
        service_2_desc: 'Intensiver Unterricht für Jugendliche und Erwachsene mit Vertiefung in die Technik der Ölmalerei. Enthüllung der Geheimnisse und Feinheiten der Erstellung von Gemälden.',
        service_3_title: 'Kunsttherapie',
        service_3_desc: 'Stressabbau und emotionale Harmonisierung durch Kreativität. Für Kinder und Erwachsene.',
        service_4_title: 'Neurographik Online',
        service_4_desc: 'Eine Praxis, die hilft, Anliegen zu bearbeiten und Lösungen durch Zeichnen zu finden. Fern verfügbar.',
        service_5_title: 'Quanten-Astrogenetik',
        service_5_desc: 'Enthüllung des planetaren Potenzials von Kindern und Erwachsenen anhand des Geburtsdatums. Empfehlungen für weitere Bildungsrichtungen und Korrektur möglicher psychologischer Zustände.',
        service_6_title: 'Lichtkarten',
        service_6_desc: 'Quanteninstrument für die Arbeit mit der feinstofflichen Ebene durch persönliche Licht-Metaphern-Legungen. "Die Unbestimmtheit von Ereignissen kann bestimmbar gemacht werden."',
        about_label: 'Über mich',
        about_title: 'Kreativität als Weg zu sich selbst',
        about_p1: 'Ich glaube, dass jedes Kind auf seine Weise talentiert ist, und meine Aufgabe ist es, dieses Talent zu entfalten. Ich unterrichte verschiedene Maltechniken mit einem individuellen Ansatz für jeden Schüler. Ich bringe Kindern bei, mit Bleistift, Acryl und Öl auf Leinwand zu malen, und entwickle kreatives Denken, künstlerische Fähigkeiten und Selbstvertrauen.',
        about_p2: 'Neben der bildenden Kunst biete ich Kunsttherapie und Neurographik für Kinder und Erwachsene an, um Stress abzubauen und das innere Gleichgewicht durch Kreativität wiederherzustellen. Ich berate auch Eltern und enthülle das planetare Potenzial der Kinder anhand ihres Geburtsdatums.',
        quote: '"Jedes Kind ist auf seine Weise talentiert, und ich bin bereit, sein Potenzial zu entfalten."',
        float_years: 'Jahre Erfahrung',
        photo_placeholder: 'Foto der Künstlerin',
        stat_1: 'Jahre kreative Erfahrung',
        stat_2: 'Jahre — Altersgruppe der Schüler',
        stat_3: 'Kunstrichtungen',
        stat_4: 'Beratungssprachen',
        gallery_label: 'Portfolio',
        gallery_title: 'Galerie',
        gallery_subtitle: 'Eigene Arbeiten und kreative Projekte von Schülern in verschiedenen Techniken.',
        gallery_tab_personal: 'Persönlich',
        gallery_tab_students: 'Schüler',
        gallery_tab_neuro: 'Neurographik',
        work_1: 'Werk 1',
        work_2: 'Werk 2',
        work_3: 'Werk 3',
        work_4: 'Werk 4',
        work_5: 'Werk 5',
        work_6: 'Werk 6',
        reviews_label: 'Bewertungen',
        reviews_title: 'Was Schüler und Eltern sagen',
        reviews_subtitle: 'Echte Bewertungen von unseren Schülern und ihren Eltern',
        video_label: 'Präsentationsvideo',
        contact_label: 'Kontakt',
        contact_title: 'Kontaktieren Sie mich',
        contact_subtitle: 'Vereinbaren Sie eine Probestunde, stellen Sie eine Frage oder erfahren Sie mehr über meine Leistungen',
        contact_info_title: 'Kontakt',
        contact_info_text: 'Schreiben oder rufen Sie an — ich antworte zu einer Zeit, die Ihnen passt.',
        form_title: 'Termin vereinbaren',
        form_text: 'Schreiben Sie mir auf Telegram, WhatsApp oder per E-Mail, und wir vereinbaren eine passende Zeit und ein passendes Format.',
        form_note: 'Unterricht und Beratungen finden in Euskirchen, online und auch zu Hause statt. Das erste Kennenlernen kann online als Beratung erfolgen, um die passende Lernmethode oder Kommunikationsform zu wählen.',
        footer_text: '© 2026 Ljudmila Krause. Alle Rechte vorbehalten.',
        gallery_more: 'Mehr Werke',
        moreworks_title: 'Alle Werke — Ljudmila Krause',
        moreworks_heading: 'Alle Werke',
        moreworks_subtitle: 'Die komplette Sammlung von Werken und Schülerprojekten',
        moreworks_empty: 'Noch keine Werke hochgeladen',
        certificates_label: 'Zertifikate',
        certificates_title: 'Meine Zertifikate',
        certificates_subtitle: 'Bestätigung der Qualifikation und beruflichen Entwicklung'
    }
};

// ... остальной код script.js без изменений ...
